apiVersion: v1
entries:
  csi-driver-nfs:
  - apiVersion: v1
    appVersion: v4.1.0
    created: "2022-07-05T06:47:20.800889706Z"
    description: CSI NFS Driver for Kubernetes
    digest: f6c513b1f58bc7508032c7609738756f8690555f0e23a3a2ba02dbbd585b7ead
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.1.0/csi-driver-nfs-v4.1.0.tgz
    version: v4.1.0
  - apiVersion: v1
    appVersion: v4.0.0
    created: "2022-07-05T06:47:20.800130103Z"
    description: CSI NFS Driver for Kubernetes
    digest: cb537287512ce9f99adaead8cd4904ed7284780bdc44c9b8d6705e66f28bfa5c
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v4.0.0/csi-driver-nfs-v4.0.0.tgz
    version: v4.0.0
  - apiVersion: v1
    appVersion: v3.1.0
    created: "2022-07-05T06:47:20.7993494Z"
    description: CSI NFS Driver for Kubernetes
    digest: 7e51bb9188b013195cafc265102fa365de9ec5513780e1dfc5363289f811a4d9
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v3.1.0/csi-driver-nfs-v3.1.0.tgz
    version: v3.1.0
  - apiVersion: v1
    appVersion: v3.0.0
    created: "2022-07-05T06:47:20.798650697Z"
    description: CSI NFS Driver for Kubernetes
    digest: 44406231cd5cdada1c62a0541b93b4f5d5a70ccc8c50b33553a8692fe6cfae96
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v3.0.0/csi-driver-nfs-v3.0.0.tgz
    version: v3.0.0
  - apiVersion: v1
    appVersion: v2.0.0
    created: "2022-07-05T06:47:20.798008295Z"
    description: CSI NFS Driver for Kubernetes
    digest: 1a32c6fc016526fe19a0c9e0dfbe83d0ddde67ced533bb5f5d24d713f706c613
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v2.0.0/csi-driver-nfs-v2.0.0.tgz
    version: v2.0.0
  - apiVersion: v1
    appVersion: latest
    created: "2022-07-05T06:47:20.797517293Z"
    description: CSI NFS Driver for Kubernetes
    digest: 6bdf28e22cf06093e29b8a4ddddfb7a5eed253e0519fa1cd2f7ce2b4ea82abb6
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/latest/csi-driver-nfs-v0.0.0.tgz
    version: v0.0.0
generated: "2022-07-05T06:47:20.796518189Z"
