apiVersion: v1
entries:
  csi-driver-nfs:
  - apiVersion: v1
    appVersion: latest
    created: "2021-12-03T09:32:27.922454757Z"
    description: CSI NFS Driver for Kubernetes
    digest: 12bfa47c9b4d8d70374af58c3ffcb17f063587ec374422290ddbaeba8be1e2d7
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/latest/csi-driver-nfs-v3.1.0.tgz
    version: v3.1.0
  - apiVersion: v1
    appVersion: v3.0.0
    created: "2021-12-03T09:32:27.923670465Z"
    description: CSI NFS Driver for Kubernetes
    digest: c19a1780bbdf240ff4628666a5cf70fea9d44fc20966b63796550e83a45ef50a
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v3.0.0/csi-driver-nfs-v3.0.0.tgz
    version: v3.0.0
  - apiVersion: v1
    appVersion: v2.0.0
    created: "2021-12-03T09:32:27.92288436Z"
    description: CSI NFS Driver for Kubernetes
    digest: f537a133eaa965f1c053ffac130f82c9b2b624e1f8bd42937c9c48818464eaac
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v2.0.0/csi-driver-nfs-v2.0.0.tgz
    version: v2.0.0
generated: "2021-12-03T09:32:27.921439951Z"
